import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from '../components/Header/Header'
import Hero from "@/sections/Hero/Hero";

//FONT AWESOME
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css'; // Importa los estilos
import WhatIncluded from "@/sections/WhatIncluded/WhatIncluded";
config.autoAddCss = false; // Evita la doble carga de CSS

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: '400'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans`}>
        <Header/>
        <Hero/>
        <WhatIncluded/>
      </body>
    </html>
  );
}
